export { default as heading_1 } from "./Heading1/Heading1"
export { default as heading_2 } from "./Heading2/Heading2"
export { default as heading_3 } from "./Heading3/Heading3"
export { default as paragraph } from "./Paragraph/Paragraph"
export { default as code } from "./Code/Code"
