import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@client/presentation/sass/global/global.scss";
import "@client/presentation/sass/global/variables.scss";

import ReactQueryProvider from "@client/shared/context/react-query/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
